/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers';
import type { FunctionFragment, Result, EventFragment } from '@ethersproject/abi';
import type { Listener, Provider } from '@ethersproject/providers';
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from '../../../../common';

export type CanDoRelayParamsStruct = { pool: string; relayer: string };

export type CanDoRelayParamsStructOutput = [string, string] & {
  pool: string;
  relayer: string;
};

export interface MystikoRelayerRegistryProxyInterface extends utils.Interface {
  functions: {
    'canDoRelay((address,address))': FunctionFragment;
    'center()': FunctionFragment;
    'changeRelayerRegistry(address)': FunctionFragment;
    'registry()': FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: 'canDoRelay' | 'center' | 'changeRelayerRegistry' | 'registry',
  ): FunctionFragment;

  encodeFunctionData(functionFragment: 'canDoRelay', values: [CanDoRelayParamsStruct]): string;
  encodeFunctionData(functionFragment: 'center', values?: undefined): string;
  encodeFunctionData(functionFragment: 'changeRelayerRegistry', values: [string]): string;
  encodeFunctionData(functionFragment: 'registry', values?: undefined): string;

  decodeFunctionResult(functionFragment: 'canDoRelay', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'center', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'changeRelayerRegistry', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'registry', data: BytesLike): Result;

  events: {
    'RelayerRegistryChanged(address)': EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: 'RelayerRegistryChanged'): EventFragment;
}

export interface RelayerRegistryChangedEventObject {
  registry: string;
}
export type RelayerRegistryChangedEvent = TypedEvent<[string], RelayerRegistryChangedEventObject>;

export type RelayerRegistryChangedEventFilter = TypedEventFilter<RelayerRegistryChangedEvent>;

export interface MystikoRelayerRegistryProxy extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MystikoRelayerRegistryProxyInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    canDoRelay(_params: CanDoRelayParamsStruct, overrides?: CallOverrides): Promise<[boolean]>;

    center(overrides?: CallOverrides): Promise<[string]>;

    changeRelayerRegistry(
      _newRegistry: string,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    registry(overrides?: CallOverrides): Promise<[string]>;
  };

  canDoRelay(_params: CanDoRelayParamsStruct, overrides?: CallOverrides): Promise<boolean>;

  center(overrides?: CallOverrides): Promise<string>;

  changeRelayerRegistry(
    _newRegistry: string,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  registry(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    canDoRelay(_params: CanDoRelayParamsStruct, overrides?: CallOverrides): Promise<boolean>;

    center(overrides?: CallOverrides): Promise<string>;

    changeRelayerRegistry(_newRegistry: string, overrides?: CallOverrides): Promise<void>;

    registry(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    'RelayerRegistryChanged(address)'(registry?: string | null): RelayerRegistryChangedEventFilter;
    RelayerRegistryChanged(registry?: string | null): RelayerRegistryChangedEventFilter;
  };

  estimateGas: {
    canDoRelay(_params: CanDoRelayParamsStruct, overrides?: CallOverrides): Promise<BigNumber>;

    center(overrides?: CallOverrides): Promise<BigNumber>;

    changeRelayerRegistry(
      _newRegistry: string,
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    registry(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    canDoRelay(_params: CanDoRelayParamsStruct, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    center(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    changeRelayerRegistry(
      _newRegistry: string,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    registry(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
