/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers';
import type { Provider } from '@ethersproject/providers';
import type { MystikoDAOGoverned, MystikoDAOGovernedInterface } from '../../contracts/MystikoDAOGoverned';

const _abi = [
  {
    inputs: [],
    name: 'center',
    outputs: [
      {
        internalType: 'contract MystikoGovernorCenter',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
] as const;

export class MystikoDAOGoverned__factory {
  static readonly abi = _abi;
  static createInterface(): MystikoDAOGovernedInterface {
    return new utils.Interface(_abi) as MystikoDAOGovernedInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): MystikoDAOGoverned {
    return new Contract(address, _abi, signerOrProvider) as MystikoDAOGoverned;
  }
}
