/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers';
import type { FunctionFragment, Result } from '@ethersproject/abi';
import type { Listener, Provider } from '@ethersproject/providers';
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from '../../../../common';

export interface IStakingActionInterface extends utils.Interface {
  functions: {
    'pause()': FunctionFragment;
    'stake(uint256)': FunctionFragment;
    'swapToStXZK(uint256)': FunctionFragment;
    'swapToXZK(uint256)': FunctionFragment;
    'unpause()': FunctionFragment;
    'withdraw(uint256)': FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: 'pause' | 'stake' | 'swapToStXZK' | 'swapToXZK' | 'unpause' | 'withdraw',
  ): FunctionFragment;

  encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
  encodeFunctionData(functionFragment: 'stake', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'swapToStXZK', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'swapToXZK', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
  encodeFunctionData(functionFragment: 'withdraw', values: [BigNumberish]): string;

  decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'stake', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'swapToStXZK', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'swapToXZK', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;

  events: {};
}

export interface IStakingAction extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IStakingActionInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    pause(overrides?: Overrides & { from?: string }): Promise<ContractTransaction>;

    stake(_amount: BigNumberish, overrides?: Overrides & { from?: string }): Promise<ContractTransaction>;

    swapToStXZK(_amount: BigNumberish, overrides?: CallOverrides): Promise<[BigNumber]>;

    swapToXZK(_amount: BigNumberish, overrides?: CallOverrides): Promise<[BigNumber]>;

    unpause(overrides?: Overrides & { from?: string }): Promise<ContractTransaction>;

    withdraw(_amount: BigNumberish, overrides?: Overrides & { from?: string }): Promise<ContractTransaction>;
  };

  pause(overrides?: Overrides & { from?: string }): Promise<ContractTransaction>;

  stake(_amount: BigNumberish, overrides?: Overrides & { from?: string }): Promise<ContractTransaction>;

  swapToStXZK(_amount: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  swapToXZK(_amount: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  unpause(overrides?: Overrides & { from?: string }): Promise<ContractTransaction>;

  withdraw(_amount: BigNumberish, overrides?: Overrides & { from?: string }): Promise<ContractTransaction>;

  callStatic: {
    pause(overrides?: CallOverrides): Promise<void>;

    stake(_amount: BigNumberish, overrides?: CallOverrides): Promise<void>;

    swapToStXZK(_amount: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    swapToXZK(_amount: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    unpause(overrides?: CallOverrides): Promise<void>;

    withdraw(_amount: BigNumberish, overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    pause(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    stake(_amount: BigNumberish, overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    swapToStXZK(_amount: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    swapToXZK(_amount: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    unpause(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    withdraw(_amount: BigNumberish, overrides?: Overrides & { from?: string }): Promise<BigNumber>;
  };

  populateTransaction: {
    pause(overrides?: Overrides & { from?: string }): Promise<PopulatedTransaction>;

    stake(_amount: BigNumberish, overrides?: Overrides & { from?: string }): Promise<PopulatedTransaction>;

    swapToStXZK(_amount: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    swapToXZK(_amount: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    unpause(overrides?: Overrides & { from?: string }): Promise<PopulatedTransaction>;

    withdraw(_amount: BigNumberish, overrides?: Overrides & { from?: string }): Promise<PopulatedTransaction>;
  };
}
