/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers';
import type { Provider } from '@ethersproject/providers';
import type {
  IMystikoRollerRegistry,
  IMystikoRollerRegistryInterface,
} from '../../../../../contracts/settings/miner/interfaces/IMystikoRollerRegistry';

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: 'address',
            name: 'pool',
            type: 'address',
          },
          {
            internalType: 'address',
            name: 'roller',
            type: 'address',
          },
          {
            internalType: 'uint256',
            name: 'rollupSize',
            type: 'uint256',
          },
        ],
        internalType: 'struct CanDoRollupParams',
        name: '_params',
        type: 'tuple',
      },
    ],
    name: 'canDoRollup',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
] as const;

export class IMystikoRollerRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IMystikoRollerRegistryInterface {
    return new utils.Interface(_abi) as IMystikoRollerRegistryInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IMystikoRollerRegistry {
    return new Contract(address, _abi, signerOrProvider) as IMystikoRollerRegistry;
  }
}
