/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers';
import type { Provider } from '@ethersproject/providers';
import type {
  IMystikoRelayer,
  IMystikoRelayerInterface,
} from '../../../../../contracts/settings/miner/interfaces/IMystikoRelayer';

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: 'address',
            name: 'pool',
            type: 'address',
          },
          {
            internalType: 'address',
            name: 'relayer',
            type: 'address',
          },
        ],
        internalType: 'struct CanDoRelayParams',
        name: '_params',
        type: 'tuple',
      },
    ],
    name: 'canDoRelay',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
] as const;

export class IMystikoRelayer__factory {
  static readonly abi = _abi;
  static createInterface(): IMystikoRelayerInterface {
    return new utils.Interface(_abi) as IMystikoRelayerInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IMystikoRelayer {
    return new Contract(address, _abi, signerOrProvider) as IMystikoRelayer;
  }
}
