/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MystikoAuditorRegistry } from './MystikoAuditorRegistry';
export type { MystikoVerifierRegistry } from './MystikoVerifierRegistry';
