/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from 'ethers';
import type { Provider, TransactionRequest } from '@ethersproject/providers';
import type {
  MystikoGovernorCenter,
  MystikoGovernorCenterInterface,
} from '../../../../contracts/governance/impl/MystikoGovernorCenter';

const _abi = [
  {
    inputs: [
      {
        internalType: 'address',
        name: '_dao',
        type: 'address',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    inputs: [],
    name: 'NotChanged',
    type: 'error',
  },
  {
    inputs: [],
    name: 'OnlyMystikoDAO',
    type: 'error',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'dao',
        type: 'address',
      },
    ],
    name: 'MystikoDAOChanged',
    type: 'event',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_newMystikoDAO',
        type: 'address',
      },
    ],
    name: 'changeMystikoDAO',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'dao',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getMystikoDAO',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
] as const;

const _bytecode =
  '0x608060405234801561001057600080fd5b5060405161023538038061023583398101604081905261002f91610054565b600080546001600160a01b0319166001600160a01b0392909216919091179055610084565b60006020828403121561006657600080fd5b81516001600160a01b038116811461007d57600080fd5b9392505050565b6101a2806100936000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c80634162169f1461004657806361070aa91461007557806390dff26114610086575b600080fd5b600054610059906001600160a01b031681565b6040516001600160a01b03909116815260200160405180910390f35b6000546001600160a01b0316610059565b61009961009436600461013c565b61009b565b005b6000546001600160a01b031633146100c65760405163177bc95160e11b815260040160405180910390fd5b6000546001600160a01b038083169116036100f4576040516336a1c33f60e01b815260040160405180910390fd5b600080546001600160a01b0319166001600160a01b038316908117825560405190917fde2e1324f3df3c01ca8d6df2ffe554430c8ad84c48bef85f850875e15f81eb8691a250565b60006020828403121561014e57600080fd5b81356001600160a01b038116811461016557600080fd5b939250505056fea26469706673582212201aea4cb6b13aea8e53f6b879100d740054779070eb311b5cd5ba392f228e14fe64736f6c63430008140033';

type MystikoGovernorCenterConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MystikoGovernorCenterConstructorParams,
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MystikoGovernorCenter__factory extends ContractFactory {
  constructor(...args: MystikoGovernorCenterConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(_dao: string, overrides?: Overrides & { from?: string }): Promise<MystikoGovernorCenter> {
    return super.deploy(_dao, overrides || {}) as Promise<MystikoGovernorCenter>;
  }
  override getDeployTransaction(_dao: string, overrides?: Overrides & { from?: string }): TransactionRequest {
    return super.getDeployTransaction(_dao, overrides || {});
  }
  override attach(address: string): MystikoGovernorCenter {
    return super.attach(address) as MystikoGovernorCenter;
  }
  override connect(signer: Signer): MystikoGovernorCenter__factory {
    return super.connect(signer) as MystikoGovernorCenter__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MystikoGovernorCenterInterface {
    return new utils.Interface(_abi) as MystikoGovernorCenterInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): MystikoGovernorCenter {
    return new Contract(address, _abi, signerOrProvider) as MystikoGovernorCenter;
  }
}
