/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from 'ethers';
import type { Provider, TransactionRequest } from '@ethersproject/providers';
import type {
  MystikoGovernorCenter,
  MystikoGovernorCenterInterface,
} from '../../../../contracts/governance/impl/MystikoGovernorCenter';

const _abi = [
  {
    inputs: [
      {
        internalType: 'address',
        name: '_dao',
        type: 'address',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    inputs: [],
    name: 'InvalidMystikoDAOAddress',
    type: 'error',
  },
  {
    inputs: [],
    name: 'OnlyMystikoDAO',
    type: 'error',
  },
  {
    inputs: [],
    name: 'OnlyOperator',
    type: 'error',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'dao',
        type: 'address',
      },
    ],
    name: 'MystikoDAOChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [],
    name: 'OperatorRenounced',
    type: 'event',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_newMystikoDAO',
        type: 'address',
      },
    ],
    name: 'changeMystikoDAO',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'dao',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getMystikoDAO',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'operator',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    name: 'previousDaos',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'renounceOperator',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_previousDao',
        type: 'address',
      },
    ],
    name: 'rollBackMystikoDAO',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
] as const;

const _bytecode =
  '0x608060405234801561001057600080fd5b506040516103db3803806103db83398101604081905261002f9161005d565b600080546001600160a01b039092166001600160a01b0319928316179055600180549091163317905561008d565b60006020828403121561006f57600080fd5b81516001600160a01b038116811461008657600080fd5b9392505050565b61033f8061009c6000396000f3fe608060405234801561001057600080fd5b506004361061007d5760003560e01c8063570ca7351161005b578063570ca735146100cf57806361070aa9146100e257806390dff261146100f3578063fef8ceb91461010657600080fd5b806326abb3fd146100825780632ab6f8db146100975780634162169f1461009f575b600080fd5b6100956100903660046102d9565b610139565b005b6100956101e4565b6000546100b2906001600160a01b031681565b6040516001600160a01b0390911681526020015b60405180910390f35b6001546100b2906001600160a01b031681565b6000546001600160a01b03166100b2565b6100956101013660046102d9565b61024a565b6101296101143660046102d9565b60026020526000908152604090205460ff1681565b60405190151581526020016100c6565b6001546001600160a01b03163314610164576040516327e1f1e560e01b815260040160405180910390fd5b6001600160a01b03811660009081526002602052604090205460ff1661019c57604051623e148760e41b815260040160405180910390fd5b600080546001600160a01b0319166001600160a01b038316908117825560405190917fde2e1324f3df3c01ca8d6df2ffe554430c8ad84c48bef85f850875e15f81eb8691a250565b6001546001600160a01b0316331461020f576040516327e1f1e560e01b815260040160405180910390fd5b600180546001600160a01b03191690556040517f28c7a5e83d73ddcbedb683cf4205e26069658d9228053225bcaacce0cdfc47dd90600090a1565b6000546001600160a01b031633146102755760405163177bc95160e11b815260040160405180910390fd5b600080546001600160a01b03908116825260026020526040808320805460ff1916600117905582549184166001600160a01b0319909216821783555190917fde2e1324f3df3c01ca8d6df2ffe554430c8ad84c48bef85f850875e15f81eb8691a250565b6000602082840312156102eb57600080fd5b81356001600160a01b038116811461030257600080fd5b939250505056fea264697066735822122048d2fe87fd087bc96c132e0884fc9605fce8485751cba959ba8e1a552f6bec5764736f6c63430008140033';

type MystikoGovernorCenterConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MystikoGovernorCenterConstructorParams,
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MystikoGovernorCenter__factory extends ContractFactory {
  constructor(...args: MystikoGovernorCenterConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(_dao: string, overrides?: Overrides & { from?: string }): Promise<MystikoGovernorCenter> {
    return super.deploy(_dao, overrides || {}) as Promise<MystikoGovernorCenter>;
  }
  override getDeployTransaction(_dao: string, overrides?: Overrides & { from?: string }): TransactionRequest {
    return super.getDeployTransaction(_dao, overrides || {});
  }
  override attach(address: string): MystikoGovernorCenter {
    return super.attach(address) as MystikoGovernorCenter;
  }
  override connect(signer: Signer): MystikoGovernorCenter__factory {
    return super.connect(signer) as MystikoGovernorCenter__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MystikoGovernorCenterInterface {
    return new utils.Interface(_abi) as MystikoGovernorCenterInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): MystikoGovernorCenter {
    return new Contract(address, _abi, signerOrProvider) as MystikoGovernorCenter;
  }
}
